### PR TITLE
Version Fix

### PR DESCRIPTION
**Pull request by vbansal-29**

### CODE REVIEW

**Comment by ltardivo** [comment]
Looks good to me!

**Comment by ClemensLey** [comment]
This is great, thanks Vishal. I created a branch upgrade-to-0.8.0-beta that fixes some other issues. If you want to you could try to merge upgrade-to-0.8.0-beta into this branch so we can merge both into the main branch together. We can talk tomorrow as well.

**Comment by vbansal-29** [comment]
Hi Clemens,
I tried to create a pull request that merged the upgrade-to-0.8.0-beta into the UI Change branch, but it gave me a message saying the two branches couldn't be automatically merged, and I don't want to mess anything up, so I didn't click submit. We can run over it on the call tomorrow! (I emailed you and Laura info on the further changes I made in case you needed context on the changes)

**Comment by ClemensLey** [comment]
Ok great, we can talk tomorrow

**Comment by ClemensLey** [comment]
Great, thanks!

**Pull request merged**
